version: "3.8"

services:
  web:
    image: registry.cn-hangzhou.aliyuncs.com/docker-images-lssh/draw-pictures-demo-next:latest
    container_name: web
    ports:
      - "3000:3000" # 修改为 Web 服务实际使用的端口
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
