version: '3'

services:
  web:
    # 修改为你的阿里云镜像仓库地址
    image: registry.cn-hangzhou.aliyuncs.com/docker-images-lssh/draw-pictures-demo-next:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
