name: CI/CD

on:
  push:
    branches:
      - master # 修改为你要触发 CI/CD 的分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clear Docker cache
        run: docker builder prune -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Alibaba Cloud
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/docker-images-lssh/draw-pictures-demo-next:latest # 修改为你的阿里云镜像仓库地址

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 你的服务器 IP 地址
          username: ${{ secrets.SERVER_USERNAME }} # 你的 SSH 用户名
          key: ${{ secrets.SERVER_SSH_KEY }} # 用于连接服务器的私钥
          script: |
            cd /home/keni/draw-pictures-demo-next
            docker-compose pull
            docker-compose down
            docker-compose up -d
