name: CI/CD

on:
  push:
    branches:
      - master # 修改为你要触发 CI/CD 的分支名称

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # 你的 Docker Hub 用户名
        password: ${{ secrets.DOCKER_PASSWORD }} # 你的 Docker Hub 密码

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lsshym9/draw-pitcure-test:latest # 修改为你的 Docker Hub 用户名和仓库名

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # 你的服务器 IP 地址
        username: ${{ secrets.SERVER_USERNAME }} # 你的 SSH 用户名
        key: ${{ secrets.SERVER_SSH_KEY }} # 用于连接服务器的私钥
        script: |
          cd /home/keni # 修改为你的项目路径
          docker-compose down
          docker-compose pull
          docker-compose up -d
